### ISSUE TITLE
Use symfony/amazon-sqs-messenger Transport for sending messages

### ISSUE THREAD

**Issue by tomcoonen** [brefphp/symfony-messenger#29]
I was wondering if it is an idea now symfony/amazon-sqs-messenger is released, to use the Transport from that package so this package handles only the serverless consumer side?
Does that make sense?

I doesn't seem right to keep that functionality in 2 places?

**Comment by mnapoli** [comment]
Hi, do you know if there are advantages or downsides for each solution?

**Comment by starred-gijs** [comment]
I can think of the following possible advantages:
- Possibility to consume via `messenger:consume` command (sandbox/development) (I have a fork for this now)
- Less maintenance, more in sync with official Symfony package (both use async-aws/sqs client internally now)
- auto-setup feature; if the SQS queue does not exist, it is created on the fly
- Fifo queues support via Stamp (including DeduplicationId)

I compared the TransportInterface:send implementations, but the are very similar, except:

1. [All headers encoded in 1 string](https://github.com/brefphp/symfony-messenger/blob/master/src/Service/Sqs/SqsTransport.php#L44) vs [each header in MessageAttribute](https://github.com/symfony/amazon-sqs-messenger/blob/master/Transport/Connection.php#L294) 
2. Support for DeduplicationId
3. Fifo support (not sure)

Possible downside:
- Less control over implementation?

**Comment by tomcoonen** [comment]
@starred-gijs you beat me to it ;)

I don't have anything to add, point 1, 2 and 3 mentioned by Gijs are most important for my use case.

Once you go serverless, you can use this package to consume the messages.
Would be nice to add some documentation on how to configure this.

**Comment by starred-gijs** [comment]
Give me a couple of days to create a PR

**Comment by tomcoonen** [comment]
@starred-gijs if I can help let me know

**Comment by starred-gijs** [comment]
@tomcoonen Would be helpful if you too could test this! 

Im using both the php and symfony serializer in my project, so I need to wait for next release, see #31 

ps: be aware that if you use the Symfony Serializer this PR will create a BC issue, because of the different way the MessageAttributes are stored.
