### ISSUE TITLE
Switching from 0.2 to 0.3.1 handle a "Access to the resource https://sqs.eu-west-3.amazonaws.com"

### ISSUE THREAD

**Issue by christophe-mailfert** [brefphp/symfony-messenger#33]
Hi all,

Thx all for the job you do.
 
I got a problem by using the bref/symfony-messenger on version 0.3.1, i got this return :

"HTTP 403 returned for \u0022https:\/\/sqs.eu-west-3.amazonaws.com\/\u0022.\"

I solved this problem by using the 0.2.0 version.

Any idea why i got this error ? Something to change in configuration ? 

Didn't see anything in changlog ;)

Thx for advance.

**Comment by mnapoli** [comment]
Hi! It seems that the URL is wrong, there is no SQS queue ID in the URL. Is the `MESSENGER_TRANSPORT_DSN` containing the full queue URL?

**Comment by mnapoli** [comment]
By the way, yes it seems we didn't write a changelog, but the configuration did change (the configuration is a bit simpler now). You can check out the readme, I'm sorry I don't have a specific upgrade docs to suggest :/

**Comment by Nyholm** [comment]
Can this be closed?

**Comment by mnapoli** [comment]
👍

**Comment by christophe-mailfert** [comment]
Oups sorry yes you can close ;)

**Comment by christophe-mailfert** [comment]
Thx for all your job guys !
