### ISSUE TITLE
Sending message to a custom event bus

### ISSUE THREAD

**Issue by kodjobaah** [brefphp/symfony-messenger#51]
Looking through `EventBridgeTransport.php` it appears it does not allow you to send events to a custom event bus.            
    [
                     'Detail' => json_encode($encodedMessage, JSON_THROW_ON_ERROR),
                    // Ideally here we could put the class name of the message, but how to retrieve it?
                    'DetailType' => 'Symfony Messenger message',
                    'Source' => $this->source,
                ]

Is this the case...or am I missing something.

**Comment by mnapoli** [comment]
It seems that you are correct 👍

**Comment by starred-gijs** [comment]
Are the any plans to support this use case? Im investigating if we can replace our custom handler to use the EventBridgeTransport, and our setup requires to be able to set **EventBusName** field of the [PutEventsRequestEntry](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEventsRequestEntry.html).

The dsn format is currently: 
`eventbridge://myapp` where `myapp` is the Source field.

My initial thought was to have a dsn like:
`eventbridge://my-bus-name-or-arn?source=myapp` but that is a BC break. so possibly makes more sense to add an query parameter like: `eventbridge://myapp?event_bus_name=my-bus-name-or-arn`

Any feedback on this? If this is useful for more people I can create a PR?

**Comment by starred-gijs** [comment]
Yes **source** is just any string and can include a `/`

If you have other ideas im happy to hear them, otherwise the query param seems to be the best choice?

**Comment by mnapoli** [comment]
Yes, something like this I'd say:

- `eventbridge://source?event-bus-name=my-bus-name`
- `eventbridge://source?event-bus-arn=my-bus-arn`

because I guess it's hard to differentiate safely between the two?

**Comment by starred-gijs** [comment]
From the [docs](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEventsRequestEntry.html)

---

**EventBusName**
The name or ARN of the event bus to receive the event. Only the rules that are associated with this event bus are used to match the event. If you omit this, the default event bus is used.

Type: String

Length Constraints: Minimum length of 1. Maximum length of 1600.

Pattern: (arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[\.\-_A-Za-z0-9]+

Required: No

---

So it can be either the bus name or ARN. 
Looking at the other [transports and their options](https://symfony.com/doc/current/messenger.html#amazon-sqs),  they use lowercase, hence my suggestion:

`eventbridge://source?event_bus_name=my-bus-name-or-arn`

**Comment by mnapoli** [comment]
Thank you for the details, you are right indeed. Your proposition sounds like the best one then!

**Comment by starred-gijs** [comment]
Great, my plan is to create a PR somewhere in the next weeks

**Comment by starred-gijs** [comment]
@kodjobaah would you be so kind to test the proposed solution in #52 ? Its always good to have another validation/test!

**Comment by starred-gijs** [comment]
@mnapoli What would be necessary to move this PR forward? (im running this implementation in production for several weeks now, no issues)

**Comment by mnapoli** [comment]
👍  just looked into that, one last thing I saw: https://github.com/brefphp/symfony-messenger/pull/52#issuecomment-992258268 and we're good for a release afterwards
