### ISSUE TITLE
SQS record with id "%s" failed to be processed. But failure was marked as unrecoverable.

### ISSUE THREAD

**Issue by Maxell92** [brefphp/symfony-messenger#76]
Hello, 

sometimes we get these two messages in our error logs:

`SQS record with id "UUID" failed to be processed. But failure was marked as unrecoverable. Message will be acknowledged.`

`unlabeled event`

These errors are logged here: https://github.com/brefphp/symfony-messenger/blob/master/src/Service/Sqs/SqsConsumer.php#L94. I am not able to reproduce this error, so it is very hard to debug.

Any idea when this error could occur? I do not know why only the message is logged and not the whole Exception. Can I send a PR logging the Exception instead of the message?

**Comment by mnapoli** [comment]
Indeed improving logs might be a good option here, a PR is welcome!

**Comment by tyx** [comment]
This issue sounds fixed in #77

**Comment by Maxell92** [comment]
Yes, thank you 👍
