### ISSUE TITLE
Allow async-aws/sqs:^2 to to support  Amazon SQS JSON API

### ISSUE THREAD

**Issue by starred-gijs** [brefphp/symfony-messenger#88]
Hi,

Do you plan to support the Amazon SQS JSON API, which is implemented in version ^2 of async-aws/sqs package https://github.com/async-aws/sqs/blob/master/CHANGELOG.md

This might be as easy as allowing         
`"async-aws/sqs": "^1.2|^2.0"`

If you are willing to merge it, I can give it a try?

**Comment by mnapoli** [comment]
Sure!
